### ISSUE TITLE
Social Icons not rendering in firefox

### ISSUE THREAD

**Issue by bhubanstha** [thesabbir/simple-line-icons#88]
Some of the social icons are not being rendered in firefox v 56.0 (32bit). To name few social-linkedin, social-twitter are not being rendered even in [official website](http://simplelineicons.com/).

**Comment by AESM** [comment]
@bhubanstha - Do you have any extensions that could be preventing social media information (links, icons, etc.) from loading?

For example, I use Ad Block Plus.  If enabled, the [Simple Line Icons preview page](http://simplelineicons.com/) won't render a handful of the social media icons.  In my case, opening Developer Tools reveals that some of the social media icon selectors have the `display: none !important;` declaration, because of an injected stylesheet courtesy of Ad Block Plus.
